### PR TITLE
Passwordless

### PR DESCRIPTION
**Pull request by porcellus**
Updated with resend functionality in mind

### CODE REVIEW

**Comment by rishabhpoddar** [comment]
# Feedback
- [ ] As per my comment in the CDI, `/{apiBasePath}/signinup/code POST` should have an input of:
   ```
   {email: string} | {phoneNumber: string} | {deviceId: string}
   ```
- [ ] Change `RESTART_FLOW` to `RESTART_FLOW_ERROR` everywhere (even in CDI please).
- [ ] There seems to be a minor types issue: When first calling `/{apiBasePath}/signinup/code POST`, a possible output is `RESTART_FLOW_ERROR`. How would the frontend handle this (it should never come here right)? This makes me think that resending the code should be a different API (In FDI and in CDI), but can we avoid this somehow?
- [ ] The output of `/{apiBasePath}/signinup/code/consume POST` has `triesLeft`, shouldn't this be `failedAttempts` instead? If we still want to keep this as `triesLeft` (which may actually be better for the UI part), we will have to return the max number of attempts in the CDI's `consume POST` API.

**Comment by porcellus** [comment]
> As per my comment in the CDI, /{apiBasePath}/signinup/code POST should have an input of:
`{email: string} | {phoneNumber: string} | {deviceId: string}`

The intention of passing the email/phoneNumber along is to enable the devs to filter/limit resends. It's doable without it (calling the Core to create a new code but sending it), but this seemed to be a better way of doing it. We could add an extra endpoint to get information about the device by the id, but it should be available on the frontend anyway. Of course, since it comes from the frontend, this needs to be checked, but we can do that by passing it along with the code creation post towards the Core.

> When first calling` /{apiBasePath}/signinup/code POST`, a possible output is RESTART_FLOW_ERROR.

This isn't a possible output during the first call, but the UI could still handle it by returning to the start of the flow, prompting the user to enter their contact info.

> If we still want to keep this as triesLeft (which may actually be better for the UI part), we will have to return the max number of attempts in the CDI's consume POST API.

We can do this, but I'm not sure if either `triesLeft` or `failedAttempts` is helpful on the login UI. Most UIs I've seen don't show them.

**Comment by rishabhpoddar** [comment]
# Feedback (in progress)
- [ ] Totally unrelated to the previous comments: The mode of operation (userIinput code vs link based vs both) would be something that's specified on the backend only. Therefore, after getting the user's input, how will the frontend know which UI to show (to enter code or display a message saying click on link on email, or both)? We should send the code types in the code creation API to the frontend. I know that we can solve this by asking the dev to input what the modes are on the frontend config too, but then they will have to put it in two places (frontend and backend) - which is more steps.
   
   Also on a related note, in terms of opening the link on another device, there are two options I see (we can do this later, but we should prepare the APIs so that these work):
      - If the user has enabled only link based, we can show a button (when the link is opened) asking the user if they should login to the original device or this one. This is only done if the current device doesn't have a deviceId (which then implies that we must store the deviceID in localstorage instead of in memory). If a deviceId is present, we use that and try to login the user (failure in logging in will result in restart flow error)
      - If the user has enabled code and link based, and if the deviceId is not present (when link is clicked), then instead of showing a button, we can show a UI saying please enter the code in the other browser, or open the link in that browser. This I think would be more secure than the option above? If we do something like this, then we would have to have a way to know what the enabled modes (link only vs both) are based on the linkCode in the URL. How would we do that in a clean way?

> The intention of passing the email/phoneNumber along is to enable the devs to filter/limit resends. It's doable without it (calling the Core to create a new code but sending it), but this seemed to be a better way of doing it. We could add an extra endpoint to get information about the device by the id, but it should be available on the frontend anyway. Of course, since it comes from the frontend, this needs to be checked, but we can do that by passing it along with the code creation post towards the Core.

I would prefer an API where we only send the deviceId to the backend to resend the code. And we can modify the `codes GET` endpoint in the CDI to also take a deviceId (xor the loginAttemptId for completness) and in the response, also return the email & phoneNumber.
   
   The reason for this is that if instead, we include the email & phoneNumber in the input, we will have to verify that the phone number and email indeed belong to the deviceId anyway (in case of rate limiting of email sending)

> This isn't a possible output during the first call, but the UI could still handle it by returning to the start of the flow, prompting the user to enter their contact info.

Yes. I guess. 

> Most UIs I've seen don't show them.

I think I have seen UIs where it's shown. If you think that we should discourage people from showing this, then we shouldn't send the count to the frontend at all.

**Comment by porcellus** [comment]
> The reason for this is that if instead, we include the email & phoneNumber in the input, we will have to verify that the phone number and email indeed belong to the deviceId anyway (in case of rate limiting of email sending)

Pushing this kind of check to the core side isn't necessarily a bad thing. I'll update the FDI and CDI and split the inputs.

> If you think that we should discourage people from showing this.

Not really, but I thought of this as something we'd just leave for user customization.

**Comment by rishabhpoddar** [comment]
- [ ] In the consume API, for the incorrect code error, we should return the maximum number of tries as well as the current failed attemp count (and likewise in the CDI)

**Comment by porcellus** [comment]
> In /{apiBasePath}/signinup/code, when sending deviceId, we should also send the loginAttemptId?

Yeah, this way, it will be available on the backend if someone wants to use it to retrieve info about the device/attempt after the token was consumed/block attempts based on that.

**Comment by rishabhpoddar** [comment]
As per our discussion on slack:
- Do we need to add codeId to APIs here? If yes, we should also add it to the magic link

**Comment by rishabhpoddar** [comment]
- [ ] Should rename `failedCodeInput` to `failedCodeInputAttemptCount`

**Comment by jscyo** [comment]
@porcellus Hey, the `user` object in the FDI spec needs to be updated to also contain the `timeJoined` field. I've made the change for version `1.10` in this [PR](https://github.com/supertokens/frontend-driver-interface/pull/31).

**Comment by rishabhpoddar** [comment]
I have already made the change in the this PR @jscyo

**Pull request merged**
